# KLUE-BERT AI 텍스트 탐지 프로젝트 설정

# 실험 설정
experiment:
  name: "klue_bert_detection"
  version: "v1.0"
  seed: 42
  
# 데이터 설정
data:
  train_file: "data/train.csv"
  test_file: "data/test.csv"
  submission_file: "data/sample_submission.csv"
  max_paragraphs_per_doc: 15
  
# 모델 설정
model:
  name: "klue/bert-base"
  num_labels: 1
  max_length: 512
  
# 훈련 설정
training:
  device: "auto"  # auto, cpu, cuda, cuda:0
  batch_size: 16
  learning_rate: 2.0e-5
  weight_decay: 0.01
  epochs: 3
  warmup_steps: 500
  gradient_accumulation_steps: 1
  max_grad_norm: 1.0
  
# 교차검증 설정
cross_validation:
  n_folds: 3
  strategy: "document_aware"  # document_aware, stratified
  shuffle: true
  
# Focal Loss 설정
focal_loss:
  alpha: 0.083  # 클래스 불균형 비율 기반
  gamma: 2.0    # 하드 샘플 집중도
  
# 조기 종료 설정
early_stopping:
  patience: 3
  min_delta: 0.001
  monitor: "val_auc"
  
# 출력 및 로깅 설정
output:
  model_dir: "models"
  log_dir: "logs"
  submission_file: "submission.csv"
  save_best_only: true
  
# 로깅 설정
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/training.log"
  
# 성능 최적화 설정
optimization:
  use_mixed_precision: true
  dataloader_num_workers: 4
  pin_memory: true
  
# 예측 설정
prediction:
  batch_size: 32
  ensemble_method: "average"  # average, weighted
  temperature_scaling: false
  
# 평가 설정
evaluation:
  metrics: ["auc", "accuracy", "precision", "recall", "f1"]
  threshold: 0.5